version: '3.9'
networks:
  seaport-net:
    driver: bridge
services:
  api:
    restart: always
    working_dir: /app
    environment:
      - APP_ENVIRONMENT=production
    image: api:v1
    command: ./seaport-orderbook 
    ports:
     - 3000:3000
    networks:
     - seaport-net