application:
  port: 8000
  hmac_secret: "super-long-and-secret-random-key-needed-to-verify-message-integrity"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: ""
  database_name: "quay"
redis_url: "redis://127.0.0.1:6379"
rpc:
  uri: "https://endpoints.omniatech.io/v1/eth/goerli/public"
  chain_id: 5
indexer:
  seaport_deploy_block: 8837775